### PR TITLE
Fix inconsistency in multi-attribute values in user info

### PR DESCRIPTION
**Pull request by ayeshajay**
**Purpose**
Fix the inconsistency between user info response and id_token values.

Fix https://github.com/wso2/product-is/issues/6575

### CODE REVIEW

**Review by sumedhe — APPROVED** [review]

**Comment by ayeshajay** [comment]
In earlier user info response was similar to
`{ "sub": "user1", "groups": "Internal/everyone,dev", "given_name": "new", "family_name": "user", "email": "user1@wso2.com" }`

But with new configurations it will similar to
`{ "sub": "user1", "groups": ["Internal/everyone","dev"], "given_name": "new", "family_name": "user", "email": "user1@wso2.com" }`

It will return multi attribute values as jason objects.

**Comment by ayeshajay** [comment]
In earlier user response was similar to
`{ "sub": "user@wso2.com", "groups": "Internal/everyone,dev", "given_name": "new", "family_name": "user", "email": "user@wso2.com" }`

But with new configurations, it will be
`{ "sub": "user@wso2.com", "groups": ["Internal/everyone","dev"], "given_name": "new", "family_name": "user", "email": "user@wso2.com" }`

multi-valued claims will return as a JSON array.

**Comment by ayeshajay** [comment]
fix https://github.com/wso2/product-is/issues/12126

**Comment by mefarazath** [comment]
@ayeshajay did we fix this test for a federated IDP login flow?

**Pull request merged**
