### PR TITLE
IDENTITY-6548: Fix subject identifier in id_token and user_info is di…

### PR DESCRIPTION
**Pull request by hasinidilanka**

### CODE REVIEW

**Comment by hasinidilanka** [comment]
@DMHP @pulasthi7 @omindu @mefarazath

**Comment by mefarazath** [comment]
@hasinidilanka  Can you check whether this fix is related to https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/440?

**Comment by hasinidilanka** [comment]
@mefarazath Yes. That fix will resolve the same issues in different manner.

**Comment by mefarazath** [comment]
Improved the fix with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/673

**Pull request closed without merging**
